src/main/java/com/ub/core/user/models/UserDoc.java
package com.ub.core.user.models;


import com.ub.core.base.role.Role;
import org.apache.commons.codec.digest.DigestUtils;
import org.bson.types.ObjectId;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.CompoundIndexes;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.util.StringUtils;

import javax.persistence.Id;
import java.io.StringWriter;
import java.text.ParseException;
import java.util.*;

@Document
@CompoundIndexes({
        @CompoundIndex(
                name = "find_by_accesstoken_new",
                def = "{'accessTokens.token': 1}"
        ),
        @CompoundIndex(
                name = "find_by_refreshtoken_new",
                def = "{'refreshTokens.token': 1}"
        ),
        @CompoundIndex(
                name = "find_by_phone",
                def = "{'phoneNumber': 1}"
        ),
        @CompoundIndex(
                name = "find_by_email",
                def = "{'email': 1}"
        )
})
public class UserDoc {

    public static String generateHexPassword(String email, String password) {
        return DigestUtils.md5Hex(email + ";" + password + "42");
    }

    public static UserToken generateNewToken(UserDoc userDoc) {
        UserToken userToken = new UserToken();
        userToken.setToken(new ObjectId().toString() + userDoc.getId() + new ObjectId().toString());
        return userToken;
    }

    @Id
    protected ObjectId id;

    protected Set<Role> roles = new HashSet<Role>();

    protected UserStatusEnum userStatus = UserStatusEnum.ACTIVE;

    protected String firstName = "";
    protected String lastName = "";


    private Long phoneNumber;
    private String passwordPhone;

    protected String email;
    protected String password;

    /**
     * отчество
     */
    protected String secondName = "";
    protected String fullName = "";

    private String vkId;
    private String vkAccessToken;
    private String vkEmail;

    private String okId;
    private String okAccessToken;
    private String okEmail;

    private String fbId;
    private String fbAccessToken;
    private String fbEmail;

    private String googleId;
    private String googleAccessToken;
    private String googleEmail;

    private String linkedinId;
    private String linkedinAccessToken;
    private String linkedinEmail;

    private String twitterId;
    private String twitterAccessToken;
    private String twitterSecretToken;
    private String twitterEmail;
    private String twitterScreenName;

    private String login;
    private String passwordForLogin;
    private String emailForLogin;

    private Integer fails = 0;
    private Date lastFailDate = new Date();

    private List<UserToken> accessTokens = new ArrayList<UserToken>();
    private List<UserToken> refreshTokens = new ArrayList<UserToken>();

    public Boolean checkAccessToken(String token) {
        for (UserToken userToken : this.accessTokens) {
            if (userToken.getToken().equals(token)) {
                return userToken.isActive();
            }
        }

        return false;
    }

    public Boolean checkRefreshToken(String token) {
        for (UserToken userToken : this.refreshTokens) {
            if (userToken.getToken().equals(token)) {
                return userToken.isActive();
            }
        }

        return false;
    }

    public UserToken getUserTokenByString(String token) {
        for (UserToken userToken : this.accessTokens) {
            if (userToken.getToken().equals(token) && userToken.isActive()) {
                return userToken;
            }
        }

        return null;
    }

    public UserToken getActiveAccessToken() {
        for (UserToken userToken : this.accessTokens) {
            if (userToken.isActive()) {
                return userToken;
            }
        }
        return null;
    }

    public UserToken getActiveRefreshToken() {
        for (UserToken userToken : this.refreshTokens) {
            if (userToken.isActive()) {
                return userToken;
            }
        }
        return null;
    }

    public String getNoNullEmail() {
        if (email != null) {
            return email;
        } else if (emailForLogin != null) {
            return emailForLogin;
        } else if (vkEmail != null) {
            return vkEmail;
        } else if (fbEmail != null) {
            return fbEmail;
        } else if (twitterEmail != null) {
            return twitterEmail;
        } else if (linkedinEmail != null) {
            return linkedinEmail;
        } else if (googleEmail != null) {
            return googleEmail;
        } else if (okEmail != null) {
            return okEmail;
        }

        return null;
    }

    public void addAccessToken(UserToken userToken) {
        this.accessTokens.add(userToken);
    }

    public void addRefreshToken(UserToken userToken) {
        this.refreshTokens.add(userToken);
    }

    public void setPasswordAsHex(String notHexPassword) {
        this.password = generateHexPassword(email, notHexPassword);
    }

    public void setPasswordForLoginAsHex(String notHexPassword) {
        this.passwordForLogin = generateHexPassword(login, notHexPassword);
    }

    public void setPasswordPhoneAsHex(String notHexPassword) {
        this.passwordPhone = generateHexPassword(phoneNumber.toString(), notHexPassword);
    }

    public boolean containsRole(Role role) {
        for (Role r : roles) {
            if (r.getId().equals(role.getId()))
                return true;
        }
        return false;
    }

    public boolean needLink() {
        return ((!StringUtils.isEmpty(getVkId())
                || !StringUtils.isEmpty(getFbId())
                || !StringUtils.isEmpty(getEmail()))
                && getPhoneNumber() == null);
    }

    public String getPasswordPhone() {
        return passwordPhone;
    }

    public void setPasswordPhone(String passwordPhone) {
        this.passwordPhone = passwordPhone;
    }

    public ObjectId getId() {
        return id;
    }

    public void setId(ObjectId id) {
        this.id = id;
    }

    public Set<Role> getRoles() {
        return roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UserStatusEnum getUserStatus() {
        return userStatus;
    }

    public void setUserStatus(UserStatusEnum userStatus) {
        this.userStatus = userStatus;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getVkId() {
        return vkId;
    }

    public void setVkId(String vkId) {
        this.vkId = vkId;
    }

    public String getVkAccessToken() {
        return vkAccessToken;
    }

    public void setVkAccessToken(String vkAccessToken) {
        this.vkAccessToken = vkAccessToken;
    }

    public String getVkEmail() {
        return vkEmail;
    }

    public void setVkEmail(String vkEmail) {
        this.vkEmail = vkEmail;
    }

    public String getFbId() {
        return fbId;
    }

    public void setFbId(String fbId) {
        this.fbId = fbId;
    }

    public String getFbAccessToken() {
        return fbAccessToken;
    }

    public void setFbAccessToken(String fbAccessToken) {
        this.fbAccessToken = fbAccessToken;
    }

    public String getFbEmail() {
        return fbEmail;
    }

    public void setFbEmail(String fbEmail) {
        this.fbEmail = fbEmail;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getPasswordForLogin() {
        return passwordForLogin;
    }

    public void setPasswordForLogin(String passwordForLogin) {
        this.passwordForLogin = passwordForLogin;
    }

    public String getEmailForLogin() {
        return emailForLogin;
    }

    public void setEmailForLogin(String emailForLogin) {
        this.emailForLogin = emailForLogin;
    }

    public String getGoogleId() {
        return googleId;
    }

    public void setGoogleId(String googleId) {
        this.googleId = googleId;
    }

    public String getGoogleAccessToken() {
        return googleAccessToken;
    }

    public void setGoogleAccessToken(String googleAccessToken) {
        this.googleAccessToken = googleAccessToken;
    }

    public String getGoogleEmail() {
        return googleEmail;
    }

    public void setGoogleEmail(String googleEmail) {
        this.googleEmail = googleEmail;
    }

    public String getTwitterId() {
        return twitterId;
    }

    public void setTwitterId(String twitterId) {
        this.twitterId = twitterId;
    }

    public String getTwitterAccessToken() {
        return twitterAccessToken;
    }

    public void setTwitterAccessToken(String twitterAccessToken) {
        this.twitterAccessToken = twitterAccessToken;
    }

    public String getTwitterEmail() {
        return twitterEmail;
    }

    public void setTwitterEmail(String twitterEmail) {
        this.twitterEmail = twitterEmail;
    }

    public String getTwitterSecretToken() {
        return twitterSecretToken;
    }

    public void setTwitterSecretToken(String twitterSecretToken) {
        this.twitterSecretToken = twitterSecretToken;
    }

    public String getTwitterScreenName() {
        return twitterScreenName;
    }

    public void setTwitterScreenName(String twitterScreenName) {

src/main/java/com/ub/core/user/models/UserEmailPasswordRecoverDoc.java
package com.ub.core.user.models;

import org.bson.types.ObjectId;
import org.springframework.data.mongodb.core.mapping.Document;

@Document
public class UserEmailPasswordRecoverDoc {
    private ObjectId id;
    private Integer counter = 0;
    private Boolean isRecovered = false;
    private ObjectId userId;
    private String code;

    public ObjectId getId() {
        return id;
    }

    public void setId(ObjectId id) {
        this.id = id;
    }

    public Integer getCounter() {
        return counter;
    }

    public void setCounter(Integer counter) {
        this.counter = counter;
    }

    public Boolean getIsRecovered() {
        return isRecovered;
    }

    public void setIsRecovered(Boolean isRecovered) {
        this.isRecovered = isRecovered;
    }

    public ObjectId getUserId() {
        return userId;
    }

    public void setUserId(ObjectId userId) {
        this.userId = userId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }
}

src/main/java/com/ub/core/user/models/UserEmailVerifiedDoc.java
package com.ub.core.user.models;

import org.bson.types.ObjectId;

import java.util.HashMap;
import java.util.Map;

public class UserEmailVerifiedDoc extends UserDoc {
    private String code;
    private Integer numberOfRetries = 0;
    private Boolean isVerified = false;
    private Map<String, ObjectId> customId = new HashMap<String, ObjectId>();

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Integer getNumberOfRetries() {
        return numberOfRetries;
    }

    public void setNumberOfRetries(Integer numberOfRetries) {
        this.numberOfRetries = numberOfRetries;
    }

    public Boolean getIsVerified() {
        return isVerified;
    }

    public void setIsVerified(Boolean isVerified) {
        this.isVerified = isVerified;
    }

    public Map<String, ObjectId> getCustomId() {
        return customId;
    }

    public void setCustomId(Map<String, ObjectId> customId) {
        this.customId = customId;
    }
}

src/main/java/com/ub/core/user/models/UserLoginStatusEnum.java
package com.ub.core.user.models;

/**
 * Created by fyzu on 16.09.16.
 */
public enum UserLoginStatusEnum {
    SUCCESS("Успешный вход"), BLOCKED("Заблокирован"), PASSWORD_ERROR("Неверный пароль");

    UserLoginStatusEnum(String title) {
        this.title = title;
    }

    private String title;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}

src/main/java/com/ub/core/user/models/UserStatusEnum.java
package com.ub.core.user.models;

public enum UserStatusEnum {
    ACTIVE, BLOCK;

    public String getTitle(){
        if(equals(ACTIVE)) return "активный";
        if(equals(BLOCK)) return "заблокирован";
        return "";
    }
}

src/main/java/com/ub/core/user/controllers/InitAdminPanelController.java
package com.ub.core.user.controllers;

import com.ub.core.base.httpResponse.ResourceNotFoundException;
import com.ub.core.base.role.BaseAdminRole;
import com.ub.core.base.role.SuperUser;
import com.ub.core.base.routes.BaseRoutes;
import com.ub.core.base.utils.RouteUtils;
import com.ub.core.user.models.UserDoc;
import com.ub.core.user.routes.UserAdminRoutes;
import com.ub.core.user.service.UserService;
import com.ub.core.user.service.exceptions.UserExistException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.ArrayList;

@Controller
public class InitAdminPanelController {

    @Autowired private UserService userService;

    @RequestMapping(value = UserAdminRoutes.INIT_USER, method = RequestMethod.GET)
    public String init() {
        ArrayList<UserDoc> all = userService.getAllUsers();
        if(all != null && all.size()>0){
            throw new ResourceNotFoundException();
        }
        return "com.ub.core.admin.user.init";
    }

    @RequestMapping(value = UserAdminRoutes.INIT_USER, method = RequestMethod.POST)
    public String init(@RequestParam String email, @RequestParam String password) throws UserExistException{
        ArrayList<UserDoc> all = userService.getAllUsers();
        if(all != null && all.size()>0){
            throw new ResourceNotFoundException();
        }

        UserDoc userDoc = new UserDoc();
        userDoc.setEmail(email);
        userDoc.setPasswordAsHex(password);
        userDoc = userService.createUserByEmail(email, password);
        userDoc.getRoles().add(new BaseAdminRole());
        userDoc.getRoles().add(new SuperUser());
        userService.save(userDoc);
        return RouteUtils.redirectTo(BaseRoutes.ADMIN);
    }

}

src/main/java/com/ub/core/user/controllers/RoleAdminController.java
package com.ub.core.user.controllers;

import com.ub.core.base.utils.RouteUtils;
import com.ub.core.role.models.RoleDoc;
import com.ub.core.role.roles.AvailableForRole;
import com.ub.core.role.service.RoleService;
import com.ub.core.security.annotationSecurity.AvailableForRoles;
import com.ub.core.user.routes.RoleAdminRoutes;
import com.ub.core.user.routes.UserAdminRoutes;
import com.ub.core.user.service.UserService;
import com.ub.core.user.views.AddEditRoleView;
import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: Anton
 * Date: 1/17/14
 * Time: 7:58 AM
 * To change this template use File | Settings | File Templates.
 */

@Controller
@AvailableForRoles(AvailableForRole.class)
public class RoleAdminController {

    @Autowired private UserService userService;
    @Autowired private RoleService roleService;
    // @Autowired private IUserDocService iUserDocService;

    @RequestMapping(value = RoleAdminRoutes.ADD, method = RequestMethod.GET)
    public String addRole(@RequestParam ObjectId id, ModelMap modelMap) {
        AddEditRoleView addEditRoleView = new AddEditRoleView();
        modelMap.addAttribute("roles", roleService.findAllRoles());
        modelMap.addAttribute("userId", id);
        return "com.ub.core.admin.role.addEdit";
    }

    @RequestMapping(value = RoleAdminRoutes.ADD, method = RequestMethod.POST)
    public String addRolePost(@RequestParam ObjectId user, @RequestParam String role, RedirectAttributes ra) {

        List<RoleDoc> roles = roleService.findAllRoles();

        for (RoleDoc r : roles) {
            if (r.getId().equals(role)) {
                userService.addRoleToUser(user, r);
                break;
            }
        }

        ra.addAttribute("id",user);
        return RouteUtils.redirectTo(UserAdminRoutes.EDIT);
    }

    @RequestMapping(value = RoleAdminRoutes.DELETE, method = RequestMethod.POST)
    public String deleteRole(@RequestParam ObjectId user, @RequestParam String role, RedirectAttributes ra) {
        List<RoleDoc> roles = roleService.findAllRoles();

        for (RoleDoc r : roles) {
            if (r.getId().equals(role)) {
                userService.deleteRoleToUser(user, r);
                break;
            }
        }

        ra.addAttribute("id", user);
        return RouteUtils.redirectTo(UserAdminRoutes.EDIT);
    }

}

src/main/webapp/WEB-INF/com/ub/core/admin/user/AddEditUserView.jsp
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
﻿
<div class="row">
    <div class="col-md-6">
        <div class="widget widget-green" id="widget_profit_chart">
            <div class="widget-title">
                <h3><i class="fa fa-tasks"></i> Добавление пользователя</h3>
            </div>
            <div class="widget-content">

                <form:form action="${backUrl}" modelAttribute="addEditUserView">

                    <form:errors path="*" cssClass="alert alert-warning" element="div"/>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="email">Email</label>
                                <form:input path="email" cssClass="form-control" id="email"/>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="password">Password</label>
                                <form:password path="password" cssClass="form-control" id="password"/>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="role">Роль</label>
                                <form:select path="role" cssClass="form-control" id="role"
                                             items="${roles}" itemValue="id" itemLabel="roleTitle"/>
                            </div>
                        </div>
                    </div>

                    <br>
                    <div class="form-group">
                        <button type="submit" id="contact-form-settings-submit" class="btn btn-primary">Сохранить
                        </button>
                    </div>
                </form:form>

            </div>
        </div>
    </div>
</div>

src/main/webapp/WEB-INF/com/ub/core/admin/user/SubMenu.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<ul class="nav">
    <li><a href="<c:url value="/admin/user/list"/>">Список пользователей</a></li>
    <li><a href="<c:url value="/admin/user/add"/>">Добавить пользователя</a></li>
</ul>

src/main/webapp/WEB-INF/com/ub/core/admin/user/UserListView.jsp
<%@ page import="com.ub.core.user.views.UserListView" %>
<%@ page import="com.ub.core.user.models.UserStatusEnum" %>
<%@ page import="com.ub.core.user.routes.UserAdminRoutes" %>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>
﻿
<div class="row">
    <form action="${url}" method="GET">
        <div class="col-lg-5">
            <div class="input-group">
                <input type="text" class="form-control input-sm" id="query" name="query"
                       value="${searchUserAdminResponse.query}" placeholder="Поиск"/>
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-sm btn-default"><i class="entypo-search">Поиск </i></button>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="widget widget-blue">
    <div class="widget-title">
        <h3><i class="fa fa-table" aria-hidden="true"></i> Пользователи</h3>
    </div>
    <div class="widget-content">
        <p>Всего - ${searchUserAdminResponse.all}</p>

        <div class="table-responsive">
            <table class="table table-bordered datatable" id="table-1">
                <thead>
                <tr>
                    <th>Email</th>
                    <th>Имя</th>
                    <th>Статус</th>
                    <th>Роли</th>
                    <th>Тип авторизации</th>
                    <th>Действия</th>

                </tr>
                </thead>
                <tbody>

                <c:forEach items="${searchUserAdminResponse.result}" var="user">
                    <tr>
                        <td>${user.noNullEmail}</td>
                        <td>${user.firstName} ${user.lastName}</td>
                        <c:if test="${user.userStatus == active}">
                            <td>
                                <span class="label label-success">Активный</span>
                            </td>
                        </c:if>
                        <c:if test="${user.userStatus == block}">
                            <td>
                                <span class="label label-danger">Не активный</span>
                            </td>
                        </c:if>
                        <td class="text-right">
                            <c:forEach items="${user.roles}" var="role">
                                ${role.roleTitle}<br/>
                            </c:forEach>
                        </td>
                        <td>
                            <c:if test="${not empty user.email}">Email;</c:if>
                            <c:if test="${not empty user.login}">Login;</c:if>
                            <c:if test="${not empty user.vkId}">Vk;</c:if>
                            <c:if test="${not empty user.fbId}">Fb;</c:if>
                            <c:if test="${not empty user.linkedinId}">LinkedIn;</c:if>
                            <c:if test="${not empty user.okId}">Ok;</c:if>
                            <c:if test="${not empty user.twitterId}">Twitter;</c:if>
                            <c:if test="${not empty user.googleId}">Google;</c:if>
                            <c:if test="${not empty user.passwordPhone}">Phone;</c:if>
                        </td>

                        <td class="text-right">
                            <c:url value="/admin/user/edit" var="editUsr">
                                <c:param name="id" value="${user.id}"/>
                            </c:url>
                            <a href="${editUsr}" class="btn btn-default btn-xs">
                                <i class="fa fa-pencil" aria-hidden="true"></i> Редактировать
                            </a>
                            <c:url value="/admin/user/delete" var="deleteUsr">
                                <c:param name="id" value="${user.id}"/>
                            </c:url>
                            <a href="${deleteUsr}" class="btn btn-xs btn-danger">
                                <i class="fa fa-times-circle" aria-hidden="true"></i> Удалить
                            </a>

                            <form action="<%= UserAdminRoutes.BLOCK%>" method="POST">
                                <input type="hidden" name="id" value="${user.id}"/>
                                <button type="submit" class="btn btn-default btn-xs">
                                    <i class="fa fa-ban" aria-hidden="true"></i> Заблокировать
                                </button>
                            </form>

                            <form action="<%= UserAdminRoutes.ACTIVE%>" method="POST">
                                <input type="hidden" name="id" value="${user.id}"/>
                                <button type="submit" class="btn btn-default btn-xs">
                                    Активировать
                                </button>
                            </form>

                        </td>
                    </tr>
                </c:forEach>

                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 text-center">
        <ul class="pagination pagination-sm">
            <c:url value="${url}" var="urlPrev">
                <c:param name="query" value="${searchUserAdminResponse.query}"/>
                <c:param name="currentPage" value="${searchUserAdminResponse.prevNum()}"/>
            </c:url>
            <li><a href="${urlPrev}"><i class="entypo-left-open-mini"></i></a></li>

            <c:forEach items="${searchUserAdminResponse.paginator()}" var="page">
                <c:url value="${url}" var="urlPage">
                    <c:param name="query" value="${searchUserAdminResponse.query}"/>
                    <c:param name="currentPage" value="${page}"/>
                </c:url>
                <li class="<c:if test="${searchUserAdminResponse.currentPage eq page}">active</c:if>">
                    <a href="${urlPage}">${page + 1}</a>
                </li>
            </c:forEach>
            <c:url value="${url}" var="urlNext">
                <c:param name="query" value="${searchUserAdminResponse.query}"/>
                <c:param name="currentPage" value="${searchUserAdminResponse.nextNum()}"/>
            </c:url>
            <li><a href="${urlNext}"><i class="entypo-right-open-mini"></i></a></li>
        </ul>
    </div>
</div>

<%--
<script type="text/javascript">
    var responsiveHelper;
    var breakpointDefinition = {
        tablet: 1024,
        phone: 480
    };
    var tableContainer;

    jQuery(document).ready(function ($) {
        tableContainer = $("#table-1");

        tableContainer.dataTable({
            "sPaginationType": "bootstrap",
            "aLengthMenu": [
                [10, 25, 50, -1],
                [10, 25, 50, "All"]
            ],
            "bStateSave": true,


            // Responsive Settings
            bAutoWidth: false,
            fnPreDrawCallback: function () {
                // Initialize the responsive datatables helper once.
                if (!responsiveHelper) {
                    responsiveHelper = new ResponsiveDatatablesHelper(tableContainer, breakpointDefinition);
                }
            },
            fnRowCallback: function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                responsiveHelper.createExpandIcon(nRow);
            },
            fnDrawCallback: function (oSettings) {
                responsiveHelper.respond();
            }
        });

        $(".dataTables_wrapper select").select2({
            minimumResultsForSearch: -1
        });
    });
</script>--%>

src/main/webapp/WEB-INF/com/ub/core/admin/user/accessDenied.jsp
<%@ page import="com.ub.core.user.routes.RoleAdminRoutes" %>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>﻿
<div class="row">
    <div class="col-md-12">
        <h1>Доступ закрыт!</h1>
        <p>К сожалению доступ закрыт.</p>
    </div>
</div>

src/main/webapp/WEB-INF/com/ub/core/admin/user/init.jsp
<%@ page import="com.ub.core.user.routes.UserAdminRoutes" %>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags" %>

<div class="row">
    <div class="col-md-12">
        <form action="<%= UserAdminRoutes.INIT_USER%>" method="POST">
            <div class="form-group">
                <label for="email">Email</label>
                <input name="email" type="email" id="email" class="form-control"/>
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input name="password" type="password" id="password" class="form-control"/>
            </div>
            <button class="btn btn-success">Создать пользователя</button>
        </form>
    </div>
</div>